### ISSUE TITLE
installation?

### ISSUE THREAD

**Issue by rockrob** [dmcfarl/RaceRenderCustomization#1]
Hi,
i'm interested....but....
how do i use these files?

**Comment by dmcfarl** [comment]
Hey @rockrob,
Unfortunately, I haven't uploaded any compiled versions just yet.  To use this immediately, you would need to clone the repository using a Java IDE such as Eclipse or IntelliJ. Then you could compile yourself. Once you have the code in an IDE, then you can run it directly by running the AutocrossDriver class. I'm hoping to make some updates soon to better support track sessions too.

I don't have access to my computer until Monday, but I'll try to upload a compiled version then with a few scripts that can run it. Then it would be as easy as downloading the JAR file and script and just running the script (assuming that you have Java installed).

**Comment by rockrob** [comment]
@dmcfarl 
thank you,i'm very glad ...
waiting your news

**Comment by dmcfarl** [comment]
@rockrob See new release: https://github.com/dmcfarl/RaceRenderCustomization/releases/tag/v0.9.0  I haven't tried to make this generalized yet, but I'll likely include track sessions shortly (since I need to put together a video for a track day shortly).
